name: ingresafe
description: A Flutter application for AI image analysis
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.21.2
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.0.4
  flutter_plugin_android_lifecycle: ^2.0.15
  google_mlkit_commons: ^0.11.0
  permission_handler: ^11.4.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  image: ^4.0.17
  url_launcher: ^6.2.5  # or the latest version
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.0 # if needed
  cloud_firestore: ^5.6.7  # or latest
  flutter_launcher_icons: ^0.14.3
  connectivity_plus: ^5.0.2
  showcaseview: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

  fonts:
    - family: zh-tw
      fonts:
        - asset: assets/fonts/NotoSansTC-Black.ttf
