// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfrffZVxDuTmtLnp_DkCS84V1ccDNCHv4',
    appId: '1:482610291689:web:bc2d924872ed9091cda178',
    messagingSenderId: '482610291689',
    projectId: 'ingresafe-dd262',
    authDomain: 'ingresafe-dd262.firebaseapp.com',
    storageBucket: 'ingresafe-dd262.firebasestorage.app',
    measurementId: 'G-XEV4GJ8JPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLRDj6pK3WlSrTPIKAnfhdSScW-KIW4Nk',
    appId: '1:482610291689:android:b3d110eb0225843acda178',
    messagingSenderId: '482610291689',
    projectId: 'ingresafe-dd262',
    storageBucket: 'ingresafe-dd262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyP7qQNsqPij7n38cDcd3pwDg7UmBKC4I',
    appId: '1:482610291689:ios:778a0b32e370a57ccda178',
    messagingSenderId: '482610291689',
    projectId: 'ingresafe-dd262',
    storageBucket: 'ingresafe-dd262.firebasestorage.app',
    iosBundleId: 'com.photoTextAi.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyP7qQNsqPij7n38cDcd3pwDg7UmBKC4I',
    appId: '1:482610291689:ios:73ebec0e4ba905ffcda178',
    messagingSenderId: '482610291689',
    projectId: 'ingresafe-dd262',
    storageBucket: 'ingresafe-dd262.firebasestorage.app',
    iosBundleId: 'com.afternoonteasafe.ingresafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfrffZVxDuTmtLnp_DkCS84V1ccDNCHv4',
    appId: '1:482610291689:web:d7b64fbcec3e8384cda178',
    messagingSenderId: '482610291689',
    projectId: 'ingresafe-dd262',
    authDomain: 'ingresafe-dd262.firebaseapp.com',
    storageBucket: 'ingresafe-dd262.firebasestorage.app',
    measurementId: 'G-KVZ65ZE7K6',
  );
}